# Generated by Django 4.2.9 on 2024-12-24 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('role_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role_name', models.CharField(default='', max_length=9000)),
                ('role_description', models.CharField(default='', max_length=9000)),
                ('role_is_active', models.BooleanField(default=True)),
                ('role_createddate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'USER ROLES',
                'db_table': 'user_roles',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UsersWithRoles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_with_role_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_with_role_createddate', models.DateField(auto_now_add=True)),
                ('user_with_role_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_name', to='Accounts.userroles')),
                ('user_with_role_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USERS WITH ROLES',
                'db_table': 'user_with_roles',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('profile_phone', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('profile_organization', models.CharField(default='', max_length=9000)),
                ('profile_type', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Organization_Admin', 'Organization Admin')], default='Organization_Admin', max_length=9000)),
                ('profile_is_active', models.BooleanField(db_index=True, default=True)),
                ('profile_created_date', models.DateField(auto_now_add=True)),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USER PROFILES',
                'db_table': 'user_profiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ForgotPasswordRequestUser',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('request_token', models.CharField(default=None, editable=False, max_length=300)),
                ('request_is_used', models.BooleanField(default=False)),
                ('request_is_active', models.BooleanField(default=True)),
                ('request_created_date', models.DateTimeField(auto_now_add=True)),
                ('request_expiration_time', models.DateTimeField()),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FORGOT PASSWORD REQUESTS',
                'db_table': 'users_forgot_password_request',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivationRequestUsers',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('account_activation_token', models.CharField(default=None, editable=False, max_length=300)),
                ('account_activation_is_used', models.BooleanField(default=False)),
                ('account_activation_is_active', models.BooleanField(default=True)),
                ('account_activation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ACCOUNT ACTIVATION REQUESTS',
                'db_table': 'account_activation_request',
                'ordering': ['-primary_key'],
            },
        ),
    ]
