# Generated by Django 5.0.6 on 2025-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0002_vendor_status_alter_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=50),
        ),
    ]
