# Generated by Django 5.0.6 on 2025-04-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0003_alter_truck_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendormission',
            name='driver',
        ),
    ]
