# Generated by Django 5.0.6 on 2025-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0004_remove_vendormission_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed'), ('Active', 'Active')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('Specialized Delivery', 'Specialized Delivery'), ('Regular Scheduled', 'Regular Scheduled'), ('Emergency', 'Emergency')], max_length=20),
        ),
    ]
