# Generated by Django 5.0.6 on 2025-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0005_alter_mission_status_alter_mission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Completed', 'Completed'), ('Active', 'Active')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('specialized', 'Specialized Delivery'), ('regular', 'Regular Scheduled'), ('emergency', 'Emergency')], max_length=20),
        ),
    ]
