# Generated by Django 5.0.6 on 2025-04-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0006_alter_mission_status_alter_mission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_id',
            new_name='unique_id',
        ),
    ]
