# Generated by Django 5.0.6 on 2025-04-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0007_remove_contact_address_remove_contact_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucksformission',
            name='cargo_items',
            field=models.ManyToManyField(blank=True, related_name='truck_assignments', to='food_track.cargoitems'),
        ),
        migrations.AddField(
            model_name='trucksformission',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_track.vendor'),
            preserve_default=False,
        ),
    ]
