# Generated by Django 5.0.6 on 2025-04-05 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0008_trucksformission_cargo_items_trucksformission_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trucksformission',
            name='cargo_items',
        ),
        migrations.CreateModel(
            name='TruckCargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transferring_quantity', models.PositiveIntegerField(help_text='Quantity of this cargo item being transferred by this truck')),
                ('cargo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_allocations', to='food_track.cargoitems')),
                ('truck_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_cargo_items', to='food_track.trucksformission')),
            ],
            options={
                'unique_together': {('truck_mission', 'cargo_item')},
            },
        ),
    ]
