# Generated by Django 5.0.6 on 2025-04-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0007_rename_mission_id_mission_unique_id'),
        ('food_track', '0009_remove_trucksformission_cargo_items_truckcargoitem'),
    ]

    operations = [
    ]
