# Generated by Django 5.0.6 on 2025-04-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0010_merge_20250405_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='unique_id',
            new_name='mission_id',
        ),
    ]
