# Generated by Django 5.0.6 on 2025-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0012_truck_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='model',
            field=models.CharField(default='toyota', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='year',
            field=models.IntegerField(default=2002),
            preserve_default=False,
        ),
    ]
