# Generated by Django 5.0.6 on 2025-04-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0013_truck_model_truck_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_id',
            new_name='unique_id',
        ),
    ]
