# Generated by Django 5.0.6 on 2025-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0014_rename_mission_id_mission_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='capacity',
            field=models.PositiveIntegerField(default=1200),
            preserve_default=False,
        ),
    ]
