# Generated by Django 5.0.6 on 2025-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0015_truck_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
