# Generated by Django 5.0.6 on 2025-05-24 21:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0016_mission_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='extra',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origin', models.CharField(help_text='Text representation of the origin address', max_length=255)),
                ('destination', models.CharField(help_text='Text representation of the destination address', max_length=255)),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates of the origin', null=True, srid=4326)),
                ('destination_point', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates of the destination', null=True, srid=4326)),
                ('path', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Full path geometry of the route', null=True, srid=4326)),
                ('travel_mode', models.CharField(choices=[('driving', 'Driving'), ('walking', 'Walking'), ('bicycling', 'Bicycling'), ('transit', 'Transit')], default='driving', max_length=20)),
                ('avoid_tolls', models.BooleanField(default=False)),
                ('avoid_highways', models.BooleanField(default=False)),
                ('optimized_waypoints', models.BooleanField(default=True)),
                ('route_data', models.JSONField(blank=True, help_text='Additional data from Google Maps API', null=True)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('active', 'Active')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='food_track.mission')),
            ],
        ),
    ]
