# Generated by Django 5.0.6 on 2025-05-24 21:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_track', '0017_remove_mission_extra_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, help_text='Collection of waypoint locations', null=True, srid=4326),
        ),
    ]
